# Passes arguments to bundle install (http://gembundler.com/man/bundle-install.1.html)
# bundler_args: --binstubs

# Specify which versions of Ruby to run the tests on; each version will be used
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
#  - jruby
  - ruby-head
  - rbx-2.0

  
# Define how to run the tests (defaults to `bundle exec rake` or `rake` depending on whether you have a `Gemfile`)
# script: "bundle exec rake rspec node"

# Define tasks to be completed before and after tests run. Will allow folding of content on frontend
before_script:
  - sh -e /etc/init.d/xvfb start
#   - command_2

# after_script:
#   - command_1
#   - command_2

# Specify an ENV variable to run before: 'bundle install' and 'rake' (or your defined 'script')
# env: "RAILS_ENV='test' "

# Specify the recipients for email notification
# notifications:
#   recipients:
#     - email-address-1
#     - email-address-2

# Disable email notifications
# notifications:
#   disabled: true
